"""Add image_url to resources

Revision ID: 181dfe76c228
Revises: 304b5a39843c
Create Date: 2025-10-20 22:52:49.982184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181dfe76c228'
down_revision = '304b5a39843c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
