"""Fix review foreign key to training_programs

Revision ID: 207c363fcee1
Revises: 360d058283d9
Create Date: 2025-10-22 01:19:08.410940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207c363fcee1'
down_revision = '360d058283d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_program_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_programs', ['program_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_program_id_fkey'), 'training_program_submissions', ['program_id'], ['id'])

    # ### end Alembic commands ###
