"""Add external_link and is_published to Resource

Revision ID: 304b5a39843c
Revises: 5b4e6c29f1bd
Create Date: 2025-10-20 13:25:15.944221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304b5a39843c'
down_revision = '5b4e6c29f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('external_link')

    # ### end Alembic commands ###
