"""Add featured and social promotion flags to JobPosting

Revision ID: 307d8f1f5a3a
Revises: c8601da7b675
Create Date: 2025-10-24 07:39:40.272613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307d8f1f5a3a'
down_revision = 'c8601da7b675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promote_on_social', sa.Boolean(), nullable=True))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smart_candidate_matching', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_talent_suggestions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bulk_messaging', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('job_post_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('employer_branding_page', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('job_boosts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_accounts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_training', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quarterly_hiring_report', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('white_label_portal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('co_branded_sponsorship', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('co_branded_sponsorship')
        batch_op.drop_column('white_label_portal')
        batch_op.drop_column('quarterly_hiring_report')
        batch_op.drop_column('onboarding_training')
        batch_op.drop_column('team_accounts')
        batch_op.drop_column('job_boosts')
        batch_op.drop_column('employer_branding_page')
        batch_op.drop_column('job_post_notifications')
        batch_op.drop_column('bulk_messaging')
        batch_op.drop_column('ai_talent_suggestions')
        batch_op.drop_column('smart_candidate_matching')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('promote_on_social')
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
