"""Add AI fields and QR path to training_programs

Revision ID: 35a8846fada5
Revises: 981dfa696a79
Create Date: 2025-10-21 01:42:32.440102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a8846fada5'
down_revision = '981dfa696a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_prompts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_landing_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_column('ai_landing_html')
        batch_op.drop_column('ai_prompts')

    # ### end Alembic commands ###
