"""Add AI flyer image field

Revision ID: 360d058283d9
Revises: f66b00a51772
Create Date: 2025-10-21 22:11:08.064284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360d058283d9'
down_revision = 'f66b00a51772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_flyer_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_column('ai_flyer_image')

    # ### end Alembic commands ###
