"""Add location column to VeteranProfile

Revision ID: 58865802298f
Revises: 307d8f1f5a3a
Create Date: 2025-10-25 15:07:58.709693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58865802298f'
down_revision = '307d8f1f5a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_plan')
    with op.batch_alter_table('veteran_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veteran_profile', schema=None) as batch_op:
        batch_op.drop_column('location')

    op.create_table('subscription_plan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_job_posts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('featured_jobs', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('analytics_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority_support', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dedicated_manager', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_plan_pkey')),
    sa.UniqueConstraint('key', name=op.f('subscription_plan_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
