"""Rename type->program_type and align fields in submissions

Revision ID: 5b4e6c29f1bd
Revises: 855692721fba
Create Date: 2025-10-19 18:40:52.374156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4e6c29f1bd'
down_revision = '855692721fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_program_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=150), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('type')
        batch_op.drop_column('phone')

    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['sharable_link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('training_program_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('program_type')

    # ### end Alembic commands ###
