"""Add trial & ai usage fields to training_partners and enterprise flag

Revision ID: 6542145d4283
Revises: 181dfe76c228
Create Date: 2025-10-21 01:05:05.109055
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6542145d4283'
down_revision = '181dfe76c228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial_active', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('trial_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_usage_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('enterprise', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_partners', schema=None) as batch_op:
        batch_op.drop_column('enterprise')
        batch_op.drop_column('ai_usage_count')
        batch_op.drop_column('trial_expiry')
        batch_op.drop_column('is_trial_active')

    # ### end Alembic commands ###
