"""Add extended fields to training_programs

Revision ID: 855692721fba
Revises: e608330e7d4f
Create Date: 2025-10-19 15:44:23.984753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '855692721fba'
down_revision = 'e608330e7d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('certification', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('how_to_apply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('facebook_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sharable_link', sa.String(length=255), nullable=True))
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('sharable_link')
        batch_op.drop_column('tiktok_link')
        batch_op.drop_column('twitter_link')
        batch_op.drop_column('linkedin_link')
        batch_op.drop_column('instagram_link')
        batch_op.drop_column('facebook_link')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('whatsapp_link')
        batch_op.drop_column('how_to_apply')
        batch_op.drop_column('duration')
        batch_op.drop_column('certification')
        batch_op.drop_column('program_type')

    # ### end Alembic commands ###
