"""Add qr_path to training_programs

Revision ID: 981dfa696a79
Revises: 6542145d4283
Create Date: 2025-10-21 01:30:35.808696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981dfa696a79'
down_revision = '6542145d4283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_column('qr_path')

    # ### end Alembic commands ###
