"""add company_logo

Revision ID: 9d715c043279
Revises: 857ec6939359
Create Date: 2026-03-30 01:25:16.790184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d715c043279'
down_revision = '857ec6939359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veteran_profile')
    op.drop_table('training_program_submissions')
    op.drop_table('training_partners')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_logo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('company_logo')

    op.create_table('training_partners',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('training_partners_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subscription_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subscription_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_trial_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('trial_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ai_usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('enterprise', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='training_partners_pkey'),
    sa.UniqueConstraint('email', name='training_partners_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('training_program_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('certification', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('social_links', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('how_to_apply', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('program_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['training_partners.id'], name=op.f('training_program_submissions_partner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_program_submissions_pkey'))
    )
    op.create_table('veteran_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_branch', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('service_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('years_of_service', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discharge_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discharge_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('deployment_history', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('profile_boosted_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('veteran_profile_user_id_fkey')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('veteran_profile_verified_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('veteran_profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('veteran_profile_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
