"""add apply fields to job postings

Revision ID: c7359ef6f547
Revises: 525d686223f2
Create Date: 2026-05-19 06:45:50.306566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7359ef6f547'
down_revision = '525d686223f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer_profile', schema=None) as batch_op:
        batch_op.drop_column('benefits')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_apply_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('how_to_apply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin_posted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('is_admin_posted')
        batch_op.drop_column('deadline')
        batch_op.drop_column('how_to_apply')
        batch_op.drop_column('external_apply_url')
        batch_op.drop_column('apply_email')

    with op.batch_alter_table('employer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
