"""Update employer and subscription models for new plans

Revision ID: c8601da7b675
Revises: 207c363fcee1
Create Date: 2025-10-24 03:40:25.402402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8601da7b675'
down_revision = '207c363fcee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer_plans')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_promotion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('analytics_access', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dedicated_manager', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('api_access', sa.Boolean(), nullable=True))
        batch_op.alter_column('plan_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('plan_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('api_access')
        batch_op.drop_column('dedicated_manager')
        batch_op.drop_column('analytics_access')
        batch_op.drop_column('social_promotion')

    op.create_table('employer_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_job_posts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_matching', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('access_preverified_veterans', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('analytics', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('job_boosts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('can_contact_candidates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_export_resumes', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority_support', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('white_label', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('api_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dedicated_account_manager', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employer_plans_pkey')),
    sa.UniqueConstraint('name', name=op.f('employer_plans_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name=op.f('employer_plans_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
