"""Add TrainingProgramSubmission and program flags

Revision ID: ccf4bc187aef
Revises: ccfc04626ed7
Create Date: 2025-10-17 19:49:49.483003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf4bc187aef'
down_revision = 'ccfc04626ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_column('is_featured')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
