"""added type, certification, duration, contact info, and apply details to training program submissions

Revision ID: d44ee06c772f
Revises: ccf4bc187aef
Create Date: 2025-10-18 02:02:02.680739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44ee06c772f'
down_revision = 'ccf4bc187aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_program_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('certification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('social_links', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('how_to_apply', sa.Text(), nullable=True))
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_program_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('how_to_apply')
        batch_op.drop_column('social_links')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('duration')
        batch_op.drop_column('certification')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
