"""Add ai_flyer_html field

Revision ID: f66b00a51772
Revises: 35a8846fada5
Create Date: 2025-10-21 21:46:09.186164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66b00a51772'
down_revision = '35a8846fada5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_flyer_html', sa.Text(), nullable=True))
        batch_op.drop_column('ai_prompts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_prompts', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('ai_flyer_html')

    # ### end Alembic commands ###
